### ISSUE TITLE
brp-create-abi can't generate abifiles.list for Python 2.x extention module

### ISSUE THREAD

**Issue by mikoim** [clearlinux/clr-rpm-config#2]
This macro try to search shared library from under ``/usr/lib64/`` but Python 2.x extention module is installed to ``/usr/lib/`` so generating abifiles.list is failed. If Clear Linux continues to support Python 2.x, this issue should be fixed.
https://github.com/clearlinux/clr-rpm-config/blob/a8ae512115fa2ef491c6b78288f9816117e09958/macros#L309-L310

```
.... TRIMMED ....
copying py2/lib.linux-x86_64-2.7/_marisa.so -> /builddir/build/BUILDROOT/python2-marisa-0.2.5-1.x86_64/usr/lib/python2.7/site-packages
copying py2/lib.linux-x86_64-2.7/_marisa.so.avx2 -> /builddir/build/BUILDROOT/python2-marisa-0.2.5-1.x86_64/usr/lib/python2.7/site-packages
copying py2/lib.linux-x86_64-2.7/marisa.py -> /builddir/build/BUILDROOT/python2-marisa-0.2.5-1.x86_64/usr/lib/python2.7/site-packages
copying py2/lib.linux-x86_64-2.7/_marisa.so.avx512 -> /builddir/build/BUILDROOT/python2-marisa-0.2.5-1.x86_64/usr/lib/python2.7/site-packages
.... TRIMMED ....
+ find /builddir/build/BUILDROOT/python2-marisa-0.2.5-1.x86_64/usr/lib64/ -maxdepth 1 -name '*.so*' -type f -print0
+ xargs -0rtn1 -P18 /usr/lib/rpm/clr/brp-create-abi
+ sort -u
find: ‘/builddir/build/BUILDROOT/python2-marisa-0.2.5-1.x86_64/usr/lib64/’: No such file or directory
.... TRIMMED ....
Processing files: python2-marisa-abi-0.2.5-1.x86_64
error: Could not open %files file /builddir/build/BUILD/marisa-0.2.5/abifiles.list: No such file or directory
```

full ``build.log`` is here.
https://gist.github.com/mikoim/2684b11c25b77752b4de6226df40cfa3

**Comment by bryteise** [comment]
Hrm I think I've forgotten about this a bit. @thiagomacieira my memory is the abifiles were not quite there for python intentionally?

**Comment by thiagomacieira** [comment]
No, this looks like a different problem.

**Comment by phmccarty** [comment]
The bug here was that `abifiles.list` was being dumped to the current directory (relative path) rather than to a fixed location (absolute path). Dumping the contents to an absolute path is better, since it removes the need for the `%install` section's script to change back to the original, toplevel build subdirectory for `%files abi -f abifiles.list` to succeed. 

I fixed the issue in the v224 release (to be pushed shortly) so that the location of that file will be an absolute path, with a path prefix of either `%{_builddir}` or `%{_builddir}/%{buildsubdir}` depending on the result of running `%setup`. This path prefix can be shortened to the conditional expansion of `%{_builddir}/%{?buildsubdir}`.

The fix will be integrated in Clear Linux OS 34530 or newer.
